# App Info
# TODO: remove icon and link once accepted in AppStore.
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : presskit.zip                                # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : "assets/icon_1024.png"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : TeXtonic                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A modern LaTeX editor and compiler for iOS and iPadOS. Coming soon.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Brian Chevalier
your_link                                 : https://twitter.com/_BrianChevalier
your_city                                 : Tempe
email_address                             : feedback@TeXtonic.app
facebook_username                         :
instagram_username                        :
twitter_username                          : TeXtonicApp
github_username                           : BrianChevalier
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Designed for iOS and iPadOS 13
    description                           : TeXtonic has been designed and architected from the ground up with modern Apple technologies to enable a more powerful and stable LaTeX editing experience.
    fontawesome_icon_name                 : bezier-curve

  - title                                 : Local Compiler
    description                           : Everything runs on your device. No need to setup a server, an internet connection, or to manually manage a TeXLive instillation.
    fontawesome_icon_name                 : mobile

  - title                                 : Robust Project Support
    description                           : TeXtonic was designed for working with complex multi-file projects. TeXtonic finds included files in your project providing tabs to quickly flip between files while still compiling from the root file.
    fontawesome_icon_name                 : folder-open

  - title                                 : Batteries Included
    description                           : Standard packages included from TeXLive. More available through the settings screen.
    fontawesome_icon_name                 : battery-full

  - title                                 : "There's an App For That"
    description                           : TeXtonic uses standard components so that your files are available to other apps. Version control your documents with Working Copy app, generate your figures with Pythonista, or preview your documents with PDFViewer.
    fontawesome_icon_name                 : share-alt

  - title                                 : Multiple Windows
    description                           : Open all your projects and PDF previews in separate windows.
    fontawesome_icon_name                 : window-restore


  - title                                 : Install More Packages
    description                           : Just drag and drop your LaTeX class and style sources files next to your main files.
    fontawesome_icon_name                 : box-open

  - title : Designed for Everyone
    description : "Engineered to work with standard accesibility technologies like: Voice Over, Voice Control, Dynamic Type, and more."
    fontawesome_icon_name : universal-access

  - title                                 : Suggestion box
    description                           : "App not meeting your needs? Found a bug? Want to suggest a feature? Open an <a href='https://github.com/brianchevalier/textonic-issue-tracker'>issue</a>."
    fontawesome_icon_name                 : envelope-open-text


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
