# App Info
# TODO: remove icon and link once accepted in AppStore.
ios_app_id                                : 1450994949                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://testflight.apple.com/join/yevwlUs1   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon_1024.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A standalone Jupyter notebooks implementation for iOS.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nicolas Holzschuch                                
your_link                                 : https://github.com/holzschu/Carnets                     
your_city                                 : Grenoble                                
email_address                             : carnets_jupyter@icloud.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : CJupyter
github_username                           : holzschu
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Run Jupyter notebooks anywhere
    description                           : The power of Jupyter notebooks. In your pocket. Anywhere. 
    fontawesome_icon_name                 : magic
    
  - title                                 : Standalone implementation
    description                           : Everything runs on your device. No need to setup a server, no need for an internet connection.
    fontawesome_icon_name                 : mobile

  - title                                 : All included
    description                           : Basic packages like Numpy, Matplotlib, Sympy are already installed. You're ready to edit notebooks.
    fontawesome_icon_name                 : play-circle

  - title                                 : Plays well with others
    description                           : Using iOS 11 filesharing ability, you can open notebooks in the Cloud, or in other apps. 
    fontawesome_icon_name                 : adjust
  
  - title                                 : Extended keyboard
    description                           : on iPads, you get an extended toolbar with basic actions on your keyboard.
    fontawesome_icon_name                 : star

  - title                                 : Install more packages
    description                           : You can add pure Python packages using `%pip` 
    fontawesome_icon_name                 : sync

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
